### ISSUE TITLE
NBS to MIDI exporting problem 

### ISSUE THREAD

**Issue by ReadThisToDie** [IoeCmcomc/NBSTool#6]
Windows x64
When I tried to export my NBS file (version 5) to MIDI, an error occurred. No costume instruments were used.
**IndexError: list index out of range**
I have this problem with only 1 file (although I haven't checked the MIDIs that I've got from other NBSes). I tried changing the length of song or BPM, deleting several layers and creating a new NBS file with the same notes, but nothing has changed. 
P.s. I'm sorry, I've already edited this comment 4-6 times:)

**Comment by IoeCmcomc** [comment]
@ReadThisToDie Thanks for your report. Does it happen with other .nbs files? Can you send me the .nbs file (or a variant of the file) causing the problem here?

**Comment by ReadThisToDie** [comment]
@IoeCmcomc this problem has only happened with one file. The other NBSes were exported normally, though I didn't listen to them.
I am only a beginner in Python, but maybe this problem is caused by a specific musical instrument, which assigns an index to a variable that is out of range, or because of using several different musical instruments in the layer.
The BPM should be 140. I will also delete this comment later, if you don't mind
![First Trumpet.zip](https://github.com/IoeCmcomc/NBSTool/files/13256149/First.Trumpet.zip)

**Comment by IoeCmcomc** [comment]
> this problem has only happened with one file. The other NBSes were exported normally, though I didn't listen to them.

@ReadThisToDie I was able to reproduce the issue. Therefore, I fixed this bug in 4a328258d1bb3a9d981665f77adcba590a33307a. I'm going to release new version soon.
Since you're interested in Python, I will explain the bug: Basically, NBSTool rearranges notes and group them by instruments before exporting to MIDI. While doing that, the actual total layers of the song may be increased or decreased, while the number of metadata layers keeps unchanged. In this case, there are notes whose layer index are greater than the number of metadata layers, hence the error.

> I will also delete this comment later, if you don't mind

In that case, I will quote important parts of your comment here to keep context for future references.
